CREATE TABLE IF NOT EXISTS trades (
    id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    size REAL NOT NULL,
    price REAL NOT NULL,
    fee REAL NOT NULL,
    ts TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS aggression_changes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    aggression INTEGER NOT NULL,
    ts TEXT NOT NULL
);
